(function () {
  window.DB_BUILD_DATA = {
    re: {
      axisLabels: ["Difficulty", "DPS", "Mobility", "Recovery", "Speed"],
      invert: [false, false, false, false, false],
      defaultPair: [0, 2],
      builds: [
        {
          id: "333-ceiling",
          name: "333 (Ceiling)",
          accent: "#ee83ab",
          pentagon: [8, 9, 5, 8.5, 8.5],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: true,
          playstyle: "Skill Reset",
          bestFor: "\u2728 Well-rounded damage ceiling",
          recommended: true,
          compareEnabled: true,
        },
        {
          id: "313-high-floor",
          name: "313 (High Floor)",
          accent: "#b39ddb",
          pentagon: [7.5, 8, 5, 9, 10],
          difficulty: 7.5,
          trixion: 1.17,
          trixionConfirmed: true,
          playstyle: "Fast & Comfy",
          bestFor: "\uD83D\uDC9C Comfort and recovery",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "111-head-hunt",
          name: "111 (Head Hunt)",
          accent: "#4db6ac",
          pentagon: [9, 8, 5, 7, 10],
          difficulty: 9,
          trixion: 1.18,
          trixionConfirmed: true,
          playstyle: "Fast & Punishing",
          bestFor: "\uD83D\uDD2A Skill expression and stagger",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "standard",
          name: "Standard",
          accent: "#8d8b93",
          pentagon: [6, 6, 8.5, 4, 6],
          difficulty: 6,
          trixion: null,
          trixionConfirmed: true,
          playstyle: "AFK Simulator",
          bestFor: "\uD83C\uDF31 Pre-Ark Grid beginner build",
          recommended: false,
          compareEnabled: true,
        },
      ],
    },
    surge: {
      axisLabels: ["Difficulty", "DPS", "Mobility", "Exposure", "Speed"],
      invert: [false, false, false, true, false],
      defaultPair: [0, 1],
      axisNoteIndex: 3,
      axisNote: "Exposure: back-attack & positional risk.",
      builds: [
        {
          id: "111-classic",
          name: "111 (Classic)",
          accent: "#ee83ab",
          pentagon: [7.5, 9, 7, 6.5, 7],
          difficulty: 7.5,
          trixion: 1.23,
          trixionConfirmed: true,
          playstyle: "Burst Combo",
          bestFor: "\uD83E\uDD81 Classic Surge gameplay",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "222-speedy",
          name: "222 (Speedy)",
          accent: "#4db6ac",
          pentagon: [7, 9, 9, 8, 8],
          difficulty: 7,
          trixion: 1.25,
          trixionConfirmed: true,
          playstyle: "Max Mobility",
          bestFor: "\uD83D\uDC06 Simple uptime focus",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "333-blitz",
          name: "333 (Blitz)",
          accent: "#b39ddb",
          pentagon: [8, 8, 8, 9, 6],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: false,
          playstyle: "Skill Reset",
          bestFor: "\uD83D\uDC2F Waiting for buffs",
          recommended: false,
          compareEnabled: true,
        },
      ],
    },
  };
})();
