(function () {
  window.DB_BUILD_DATA = {
    re: {
      axisLabels: ["Difficulty", "DPS", "Mobility", "Recovery", "Speed"],
      invert: [false, false, false, false, false],
      defaultPair: [0, 2],
      builds: [
        {
          id: "333-ceiling",
          name: "333 (Ceiling)",
          accent: "#ec91b2",
          pentagon: [8, 9, 5, 8.5, 8.5],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: true,
          playstyle: "Skill Reset",
          emoji: "\u2728",
          words: "skill reset",
          desc: "Well-rounded build that offers the highest RE damage. Sensitive to high ping or low FPS.",
          ark: "full",
          recommended: true,
          compareEnabled: true,
        },
        {
          id: "313-high-floor",
          name: "313 (High Floor)",
          accent: "#baa4e2",
          pentagon: [7.5, 8, 5, 9, 10],
          difficulty: 7.5,
          trixion: 1.17,
          trixionConfirmed: true,
          playstyle: "Fast & Comfy",
          emoji: "\uD83D\uDC9C",
          words: "comfort \u2022 transitional",
          desc: "A faster, simpler, more forgiving Fatal Wave build with a lower damage ceiling.",
          ark: "little",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "111-head-hunt",
          name: "111 (Head Hunt)",
          accent: "#6ac7be",
          pentagon: [9, 8, 5, 7, 10],
          difficulty: 9,
          trixion: 1.18,
          trixionConfirmed: true,
          playstyle: "Fast & Punishing",
          emoji: "\uD83D\uDD2A",
          words: "challenging \u2022 old meta",
          desc: "Fast, punishing build with little recovery, but high skill expression.",
          ark: "little",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "standard",
          name: "Standard",
          accent: "#e2c575",
          pentagon: [6, 6, 8.5, 4, 6],
          difficulty: 6,
          trixion: null,
          trixionConfirmed: true,
          playstyle: "AFK Simulator",
          emoji: "\uD83C\uDF31",
          words: "beginner \u2022 legacy",
          desc: "Simple to learn, with some downtime.",
          ark: "none",
          recommended: false,
          compareEnabled: true,
        },
      ],
    },
    surge: {
      axisLabels: ["Difficulty", "DPS", "Mobility", "Exposure", "Speed"],
      invert: [false, false, false, true, false],
      defaultPair: [0, 1],
      axisNoteIndex: 3,
      axisNote: "Exposure: back-attack & positional risk.",
      builds: [
        {
          id: "111-classic",
          name: "111 (Classic)",
          accent: "#ec91b2",
          pentagon: [7.5, 9, 7, 6.5, 7],
          difficulty: 7.5,
          trixion: 1.23,
          trixionConfirmed: true,
          playstyle: "Burst Combo",
          emoji: "\uD83E\uDD81",
          words: "bursty \u2022 familiar",
          desc: "Builds up to one massive hit. Strongest burst combo, but it needs careful execution.",
          ark: "little",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "222-speedy",
          name: "222 (Speedy)",
          accent: "#6ac7be",
          pentagon: [7, 9.5, 9, 8, 8],
          difficulty: 7,
          trixion: 1.25,
          trixionConfirmed: true,
          playstyle: "Cycle Combos",
          emoji: "\uD83D\uDC06",
          words: "cycle combos",
          desc: "Uptime-focused and mobile: easy to pick up, hard to master. It's exactly as good as you are.",
          ark: "little",
          recommended: true,
          compareEnabled: true,
        },
        {
          id: "333-blitz",
          name: "333 (Blitz)",
          accent: "#baa4e2",
          pentagon: [8, 8, 8, 9, 6],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: false,
          playstyle: "Skill Reset",
          emoji: "\uD83D\uDC2F",
          words: "skill reset",
          desc: "Fun, but too impractical for the damage it offers.",
          ark: "full",
          viable: false,
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "pre-ark-grid",
          name: "Surge",
          accent: "#6ac7be",
          emoji: "\uD83C\uDF31",
          words: "beginner \u2022 modern",
          desc: "Essentially 111 (Classic) with minor adjustments.",
          ark: "none",
          recommended: false,
          compareEnabled: false,
        },
      ],
    },
  };
})();
