(function () {
  window.DB_SKILL_NAMES = {
    voidstrike: "Void Strike",
    twinshadows: "Twin Shadows",
    soulabsorber: "Soul Absorber",
    deathsentence: "Death Sentence",
    fatalwave: "Fatal Wave",
    windcut: "Wind Cut",
    deathtrance: "Death Trance",
    surpriseattack: "Surprise Attack",
    breakingmoon: "Breaking Moon",
    bladedance: "Blade Dance",
    darkaxel: "Dark Axel",
    upperslash: "Upper Slash",
    fallstar: "Fallstar",
    maelstrom: "Maelstrom",
    turningslash: "Turning Slash",
    deathlyslash: "Deathly Slash",
    surge: "Surge",
    bladeassault: "Blade Assault",
    flashblink: "Flash Blink",
    blitzrush: "Blitz Rush",
    earthcleaver: "Earth Cleaver",
    headhunt: "Head Hunt",
    spincutter: "Spincutter",
    atropine: "Atropine",
    stimulant: "Stimulant",
    striploin: "Striploin Steak Meal",
    steak: "Herb Steak Meal",
    azena: "Azena's Blessing",
    feast: "Atk/Move Speed Feast",
    vernesewine: "Vernese Wine",
    ealynsblessing: "Ealyn's Blessing",
    grudge: "Grudge",
    ambushmaster: "Ambush Master",
    raidcaptain: "Raid Captain",
    adrenaline: "Adrenaline",
    keenbluntweapon: "Keen Blunt Weapon",
    curseddoll: "Cursed Doll",
    massincrease: "Mass Increase",
    maxmp: "Max MP Increase",
    spiritabsorption: "Spirit Absorption",
    bleed: "Bleed",
  };
})();
