#!/usr/bin/env python3
"""Keep the Order Core Comparison's damage shares in step with the build pages.

docs/javascripts/order-core-data.js holds one object of skill shares per
calculator build, copied from that build page's dps-chart block. This script
rewrites that block from the pages (default), or only reports drift (--check,
which check_content.py also runs so a stale block fails the deploy).

Usage:
  python3 scripts/sync_order_core_shares.py           rewrite the block
  python3 scripts/sync_order_core_shares.py --check   exit 1 if it is stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "javascripts" / "order-core-data.js"
OPTIONS = ROOT / "docs" / "javascripts" / "core-options-data.js"

# Calculator build id (BRACE_SPEC_BUILDS key) -> the page whose dps-chart it uses.
BUILD_PAGES = {
    "re-111": "docs/remaining-energy/111-head-hunt.md",
    "re-333": "docs/remaining-energy/333-ceiling.md",
    "surge-111": "docs/surge/111-classic.md",
    "surge-222": "docs/surge/222-speedy.md",
    "surge-333": "docs/surge/333-blitz.md",
}

BEGIN = "    // BEGIN SHARES (generated by scripts/sync_order_core_shares.py)\n"
END = "    // END SHARES\n"
CHART = re.compile(r'<div class="dps-chart"[^>]*?data-values="([^"]*)"[^>]*?data-ids="([^"]*)"')


def read_shares():
    out = {}
    for build, rel in BUILD_PAGES.items():
        m = CHART.search((ROOT / rel).read_text())
        if not m:
            raise SystemExit(f"{rel}: no dps-chart with data-values and data-ids")
        values = [v.strip() for v in m.group(1).split(",")]
        ids = [i.strip() for i in m.group(2).split(",")]
        if len(values) != len(ids):
            raise SystemExit(f"{rel}: dps-chart data-values and data-ids differ in length")
        out[build] = dict(zip(ids, (float(v) for v in values)))
    return out


def render(shares):
    lines = ["    shares: {\n"]
    for build, skills in shares.items():
        body = ", ".join(f"{sid}: {v:g}" for sid, v in skills.items())
        lines.append(f'      "{build}": {{ {body} }},\n')
    lines.append("    },\n")
    return BEGIN + "".join(lines) + END


def current_block(text):
    a, b = text.find(BEGIN), text.find(END)
    if a < 0 or b < 0:
        raise SystemExit(f"{DATA}: BEGIN/END SHARES markers missing")
    return a, b + len(END)


CORE_ENTRY = re.compile(r'"([^"]+)":\s*\{[^{}]*?relic:\s*([\d.]+),\s*ancient:\s*([\d.]+)[^{}]*\}')
SUMMARY = re.compile(r'summary:\s*"((?:[^"\\]|\\.)*)"')
LINE_17P = r'bp:\s*"17P",\s*text:\s*"((?:[^"\\]|\\.)*)"'


def check_lines():
    """Each core's relic and ancient figures must appear as a relic/ancient pair
    in its 17P line in core-options-data.js (that line is what the table shows)."""
    problems = []
    data = DATA.read_text()[DATA.read_text().find("cores:"):]
    options = OPTIONS.read_text()
    for m in CORE_ENTRY.finditer(data):
        label, relic, ancient = m.group(1), m.group(2), m.group(3)
        summary = SUMMARY.search(m.group(0))
        pair = f"{float(relic) * 100:.1f}%/{float(ancient) * 100:.1f}%"
        entry = re.search(r'"' + re.escape(label) + r'":\s*\{\s*options:\s*\[(.*?)\n      \]', options, re.S)
        line = re.search(LINE_17P, entry.group(1)) if entry else None
        if not line:
            problems.append(f"{OPTIONS.relative_to(ROOT)}: no 17P line for Order core {label!r}")
        elif not summary or pair not in summary.group(1):
            problems.append(f"{DATA.relative_to(ROOT)}: {label!r} summary lacks {pair!r}")
        if line and pair not in line.group(1):
            problems.append(f"{OPTIONS.relative_to(ROOT)}: {label!r} 17P line lacks {pair!r}, "
                            "which order-core-data.js says its relic/ancient bonus is")
    return problems


def check():
    """Return a list of problem strings (empty when the block matches the pages)."""
    text = DATA.read_text()
    a, b = current_block(text)
    problems = check_lines()
    if text[a:b] != render(read_shares()):
        problems.append(f"{DATA.relative_to(ROOT)}: Order Core shares differ from the build pages' dps-chart "
                        "blocks; run python3 scripts/sync_order_core_shares.py")
    return problems


def main():
    if "--check" in sys.argv:
        problems = check()
        for p in problems:
            print(p)
        sys.exit(1 if problems else 0)
    text = DATA.read_text()
    a, b = current_block(text)
    DATA.write_text(text[:a] + render(read_shares()) + text[b:])
    print("shares rewritten")


if __name__ == "__main__":
    main()
